- type: web
  name: keycloak
  runtime: docker
  plan: free
  dockerfilePath: ./keycloak/Dockerfile
  dockerContext: ./keycloak
  healthCheckPath: /health/ready
  envVars:
    - key: KC_DB
      value: postgres
    - key: KC_DB_URL
      sync: false
    - key: KC_DB_USERNAME
      sync: false
    - key: KC_DB_PASSWORD
      sync: false
    - key: KEYCLOAK_ADMIN
      value: admin
    - key: KEYCLOAK_ADMIN_PASSWORD
      sync: false
    - key: KC_HOSTNAME_STRICT
      value: "false"
    - key: KC_HTTP_ENABLED
      value: "true"
    - key: KC_PROXY
      value: edge
    - key: KC_HEALTH_ENABLED
      value: "true"